# Generated by Django 5.2.3 on 2025-06-30 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bodega',
            new_name='SGI_M_BODEGA',
        ),
        migrations.RenameModel(
            old_name='Empleado',
            new_name='SGI_M_EMPLEADO',
        ),
        migrations.RenameModel(
            old_name='Producto',
            new_name='SGI_M_PRODUCTO',
        ),
        migrations.RenameModel(
            old_name='Proveedor',
            new_name='SGI_M_PROVEEDOR',
        ),
        migrations.RenameModel(
            old_name='Stand',
            new_name='SGI_M_STAND',
        ),
        migrations.RenameModel(
            old_name='Categoria',
            new_name='SGI_P_CATEGORIA',
        ),
        migrations.RenameModel(
            old_name='Ciudad',
            new_name='SGI_P_CIUDAD',
        ),
        migrations.RenameModel(
            old_name='Marca',
            new_name='SGI_P_MARCA',
        ),
        migrations.RenameModel(
            old_name='Pais',
            new_name='SGI_P_PAIS',
        ),
        migrations.RenameModel(
            old_name='Rol',
            new_name='SGI_P_ROL',
        ),
        migrations.RenameModel(
            old_name='RotacionInventario',
            new_name='SGI_P_ROTACIONINVENTARIO',
        ),
        migrations.RenameModel(
            old_name='TipoInventario',
            new_name='SGI_P_TIPOINVENTARIO',
        ),
        migrations.RenameModel(
            old_name='Inventario',
            new_name='SGI_T_INVENTARIO',
        ),
        migrations.RenameModel(
            old_name='InventarioStand',
            new_name='SGI_T_INVENTARIOSTAND',
        ),
        migrations.RenameModel(
            old_name='RegistroInventario',
            new_name='SGI_T_REGISTROINVENTARIO',
        ),
    ]
